package NapakalakiGame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.Timer;


public class Dice extends JDialog {
  
  private static Dice instance = null;
  private Random generator=new Random();
  private Timer timerDice;
  private int value;
    
  private Dice (JFrame parent) {
    super(parent, true);
    
    initComponents();
    timerDice = new Timer (50,diceAction);
    this.addWindowListener(new java.awt.event.WindowAdapter() {
      @Override
      public void windowClosing(java.awt.event.WindowEvent e) {
        System.exit(0);
      }
    });
  }

  public static void createInstance (JFrame parent) {
    if (instance == null)
      instance = new Dice (parent);
  }
  
  public static Dice getInstance() {
      return instance;
  }
  
  private int privateNextNumber() {
    return (generator.nextInt(6)+1);
  }
  
  private ActionListener diceAction = new ActionListener() {
    @Override
    public void actionPerformed (ActionEvent ev) {
        value = privateNextNumber();
        jL_dice.setText(Integer.toString(value));
        pack();
      }
    };
  
  public int nextNumber () {
    return nextNumber ("Puedes llamar al método",
            "Pasándole 2 cadenas como parámetros");
    
  }
  public int nextNumber (String message1, String message2) {
    jB_OK.setVisible(false);
    jL_message1.setText(message1);
    jL_message2.setText(message2);
    pack();
    timerDice.start();
    this.setVisible(true);
    return value;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_dice = new javax.swing.JLabel();
        jL_message1 = new javax.swing.JLabel();
        jB_OK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jL_message2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dado");
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_dice.setBackground(new java.awt.Color(255, 255, 255));
        jL_dice.setFont(new java.awt.Font("Trebuchet MS", 2, 48)); // NOI18N
        jL_dice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_dice.setText("1");
        jL_dice.setOpaque(true);
        jL_dice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_diceMouseClicked(evt);
            }
        });
        getContentPane().add(jL_dice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 80, 80));

        jL_message1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jL_message1.setForeground(new java.awt.Color(204, 204, 204));
        jL_message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_message1.setText("jLabel1");
        getContentPane().add(jL_message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 30));

        jB_OK.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB_OK.setText("OK");
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });
        getContentPane().add(jB_OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 60, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pincha sobre el dado para detenerlo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 250, -1));

        jL_message2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jL_message2.setForeground(new java.awt.Color(204, 204, 204));
        jL_message2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_message2.setText("jLabel1");
        getContentPane().add(jL_message2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 350, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dados.gif"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        setSize(new java.awt.Dimension(410, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void jL_diceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_diceMouseClicked
    timerDice.stop();
    jB_OK.setVisible(true);
    pack();
  }//GEN-LAST:event_jL_diceMouseClicked

  private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
    this.dispose();
  }//GEN-LAST:event_jB_OKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jB_OK;
    private javax.swing.JLabel jL_dice;
    private javax.swing.JLabel jL_message1;
    private javax.swing.JLabel jL_message2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
