/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MusicPlayer.MusicPlayer;
import java.util.ArrayList;

/**
 *
 */

public class MusicPlayerView extends javax.swing.JPanel {
    
    private MusicPlayer player = null;
    ArrayList<String> Files = new ArrayList();
    
    /**
     * Creates new form MusicPlayer
     */
    
    public MusicPlayerView() {
        initComponents();
        select.setSelected(true);
        select.setOpaque(false);
    }

    public void reproducirAudio(ArrayList<String> archivos) {
        
        Files = archivos;
        player = new MusicPlayer(archivos);
        player.start();
    }
    
    public void cerrarAudio() {
        
        player.Stop();
        try { player.join(); }
        catch (Exception e) {}
    }
    
    /*public void cerrarAudio(String archivo) {
        
        player.close();
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.JRadioButton();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(63, 22));
        setMinimumSize(new java.awt.Dimension(63, 22));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        select.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        select.setForeground(new java.awt.Color(204, 204, 204));
        select.setText("Música");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
       
        boolean seleccionado = select.isSelected();
        
        if (!seleccionado)
            
            cerrarAudio();
        
        else 
            
            reproducirAudio(Files);
    }//GEN-LAST:event_selectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton select;
    // End of variables declaration//GEN-END:variables
}
