/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 */
public class PlayerNamesCapture extends javax.swing.JDialog {

    ArrayList<String> names = new ArrayList();
    int numJugador;
    ArrayList<String> canciones = new ArrayList();
    
    
    public PlayerNamesCapture(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        
        numJugador = 1;
        
        PlayButton.setEnabled(false);
        
        this.addWindowListener (new WindowAdapter() {
            
            @Override
            public void windowClosing (WindowEvent e) {
                
                System.exit(0);
            }
        });
        
        TextPlayer.setText("Jugador " + numJugador + ":");
        
        canciones.add("/Resources/Music/introNap.mp3"); // Añade canciones
        music.reproducirAudio(canciones); //Reproduce las Canciones
        
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextPlayer1 = new javax.swing.JLabel();
        music = new GUI.MusicPlayerView();
        CuadroOp = new javax.swing.JPanel();
        PlayButton = new javax.swing.JButton();
        TextPlayer = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        SetName = new javax.swing.JTextField();
        aniade = new javax.swing.JButton();
        errorname = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Napakalaki");
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setPreferredSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        TextPlayer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TextPlayer1.setForeground(new java.awt.Color(204, 204, 204));
        TextPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextPlayer1.setText("NAPAKALAKI");
        getContentPane().add(TextPlayer1);
        TextPlayer1.setBounds(0, 11, 900, 22);
        getContentPane().add(music);
        music.setBounds(20, 490, 63, 22);

        CuadroOp.setMaximumSize(new java.awt.Dimension(380, 168));
        CuadroOp.setMinimumSize(new java.awt.Dimension(380, 168));
        CuadroOp.setOpaque(false);
        CuadroOp.setPreferredSize(new java.awt.Dimension(380, 168));

        PlayButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        PlayButton.setText("Jugar");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        TextPlayer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextPlayer.setForeground(new java.awt.Color(204, 204, 204));
        TextPlayer.setText("Jugador ");

        CancelButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SetName.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        SetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetNameActionPerformed(evt);
            }
        });

        aniade.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        aniade.setText("Añadir Jugador");
        aniade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadeActionPerformed(evt);
            }
        });

        errorname.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        errorname.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout CuadroOpLayout = new javax.swing.GroupLayout(CuadroOp);
        CuadroOp.setLayout(CuadroOpLayout);
        CuadroOpLayout.setHorizontalGroup(
            CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadroOpLayout.createSequentialGroup()
                .addGroup(CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorname, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CuadroOpLayout.createSequentialGroup()
                            .addComponent(SetName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(aniade))
                        .addComponent(CancelButton)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        CuadroOpLayout.setVerticalGroup(
            CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPlayer)
                    .addComponent(SetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aniade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorname, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(CuadroOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        getContentPane().add(CuadroOp);
        CuadroOp.setBounds(260, 127, 400, 168);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cartas.gif"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 900, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed

        this.dispose();
        music.cerrarAudio();
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetNameActionPerformed

    private void aniadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadeActionPerformed
        
        if (SetName.getText().length() > 0 && SetName.getText().length() < 25) {
            
            boolean repetido = false;
           
            for(int i = 0 ; i < names.size() ; i++)
                
                if(SetName.getText().contentEquals(names.get(i)))
                    
                   repetido = true;
            
                    
            if(repetido){
                
                errorname.setText("Nombre en uso.");
                SetName.setText("");
            }
            
            else{
            
                PlayButton.setEnabled(true);

                errorname.setText("");

                names.add (SetName.getText());

                numJugador++;

                TextPlayer.setText("Jugador "+ numJugador + ":");

                SetName.setText("");
            }
        }
        
        else {
            
            errorname.setText("Tamaño de nombre incorrecto");
            
            SetName.setText("");
        }
        
        if (numJugador == 4){
            
            aniade.setEnabled(false);
            
            SetName.setEnabled(false);
            
            TextPlayer.setText("Max.Jugadores");
            
        }
        
        repaint();
    }//GEN-LAST:event_aniadeActionPerformed

    public ArrayList<String> getNames(){
        
        this.setVisible(true);
        return names;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel CuadroOp;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextField SetName;
    private javax.swing.JLabel TextPlayer;
    private javax.swing.JLabel TextPlayer1;
    private javax.swing.JButton aniade;
    private javax.swing.JLabel errorname;
    private GUI.MusicPlayerView music;
    // End of variables declaration//GEN-END:variables
}
